### ISSUE TITLE
samples/synchronous.js doesn't work (also in the README.md)

### ISSUE THREAD

**Issue by joshux** [wdavidw/node-stream-transform#7]
I ran:  node samples/synchronous.js
outputs:

  data.push(data.shift());
                 ^
TypeError: Object TypeError: Cannot read property 'length' of undefined has no method 'shift'
    at /home/joshux/Dropbox/node-stream-transform-play/node-stream-transform/samples/synchronous.js:8:18
    at null.<anonymous> (/home/joshux/Dropbox/node-stream-transform-play/node-stream-transform/lib/index.js:70:14)
    at EventEmitter.emit (events.js:95:17)
    at Transformer._done (/home/joshux/Dropbox/node-stream-transform-play/node-stream-transform/lib/index.js:139:17)
    at Transformer._transform (/home/joshux/Dropbox/node-stream-transform-play/node-stream-transform/lib/index.js:122:17)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at Writable.write (_stream_writable.js:180:11)

**Comment by charitha-bridg** [comment]
+1 i'm experiencing the same issue. I think the code was updated and the documentation is stale. I see the same problem throughout the docs.
